### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by adder46**
@PurpleMyst

Would you say this is cleaner than what's on the master branch currently?

### CODE REVIEW

**Review by PurpleMyst — APPROVED** [review]
LGTM! However I don't understand why you return a `String` from certain functions where a `&'static str` would suffice

**Comment by adder46** [comment]
@PurpleMyst, presumably, you're referring to `fn`'s in `formatter`? Yeah, I'll change that.

What I don't like is that almost everything in `ui.rs` takes `commands` as an argument.

**Comment by PurpleMyst** [comment]
Why is `commands` a HashMap with an enum key instead of a struct?

**Comment by adder46** [comment]
@PurpleMyst, I wasn't able to make `UserInterface` have a reference to `Application`, since that required `UserInterface` to borrow `application` as immutable, and later on `application` was mutated (`toggle_case()` and stuff).

Can you think of a workaround?

**Pull request merged**
